# Generated by Django 2.0.4 on 2018-11-28 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=300, null=True)),
                ('date', models.DateField(null=True)),
                ('location', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('closed', models.BooleanField()),
                ('note', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('note', models.CharField(max_length=100, null=True)),
                ('num_spaces', models.PositiveIntegerField(default=10)),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ss_app.Days')),
            ],
        ),
        migrations.CreateModel(
            name='FocusAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_area', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_date', models.DateField(auto_now_add=True)),
                ('items_discussed', models.TextField(null=True)),
                ('follow_ups', models.TextField(null=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ss_app.Appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('available', models.CharField(choices=[('B', 'Booked'), ('C', 'Closed'), ('O', 'Open'), ('R', 'Requested')], max_length=1)),
                ('comments', models.CharField(max_length=100, null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ss_app.Staff')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='ss_app.Days')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ss_app.TimeSlots'),
        ),
        migrations.AddField(
            model_name='client',
            name='coverage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ss_app.Staff'),
        ),
        migrations.AddField(
            model_name='client',
            name='focus_areas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ss_app.FocusAreas'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ss_app.Client'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appt', to='ss_app.TimeSlots'),
        ),
    ]
