# Generated by Django 2.0.4 on 2018-11-29 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ss_app', '0003_auto_20181128_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appt', to='ss_app.TimeSlots'),
        ),
        migrations.AlterField(
            model_name='client',
            name='focus_areas',
            field=models.ManyToManyField(to='ss_app.FocusAreas'),
        ),
    ]
