# Generated by Django 2.0.4 on 2018-11-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_app', '0005_appointment_message_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='location',
            field=models.TextField(choices=[('1', 'Our Office'), ('2', 'Your Office'), ('3', 'Other (please include in message)')], max_length=100, null=True),
        ),
    ]
