# Generated by Django 2.0.4 on 2018-11-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_app', '0006_auto_20181129_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='location',
            field=models.TextField(choices=[('1', 'Our Office'), ('2', 'Your Office (please include location in message)'), ('3', 'Other (please include in message)')], max_length=100, null=True),
        ),
    ]
