# Generated by Django 2.0.4 on 2018-12-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_app', '0007_auto_20181130_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslots',
            name='cal_event_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='location',
            field=models.TextField(choices=[('1', 'Our Office'), ('2', 'Your Office (please include location in comments)'), ('3', 'Other (please include location in comments)')], max_length=100, null=True),
        ),
    ]
