# Generated by Django 2.0.4 on 2018-12-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_app', '0008_auto_20181218_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslots',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
