# Generated by Django 2.0.4 on 2018-12-18 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ss_app', '0009_timeslots_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appt', to='ss_app.TimeSlots'),
        ),
    ]
