# Generated by Django 2.0.4 on 2018-12-19 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ss_app', '0011_auto_20181219_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslots',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss_app.Staff'),
        ),
    ]
