# Generated by Django 2.0.4 on 2019-01-16 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ss_app', '0013_auto_20181220_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('status', models.CharField(max_length=30)),
                ('inv_date', models.DateField()),
                ('Appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss_app.Appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss_app.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=30)),
                ('num_of_sessions', models.PositiveIntegerField()),
                ('mtg_duration', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('paid_date', models.DateField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss_app.Invoice')),
            ],
        ),
        migrations.RemoveField(
            model_name='notes',
            name='paid',
        ),
        migrations.AddField(
            model_name='client',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ss_app.Package'),
        ),
    ]
