# Generated by Django 2.0.4 on 2019-01-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss_app', '0015_auto_20190117_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='Appointment',
            new_name='appointment',
        ),
    ]
