# Generated by Django 2.0.4 on 2019-01-18 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ss_app', '0016_auto_20190118_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ss_app.Package'),
        ),
    ]
