# Generated by Django 2.0.4 on 2019-01-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_app', '0017_invoice_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='note',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
