# Generated by Django 2.0.4 on 2019-01-19 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ss_app', '0018_invoice_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ss_app.Appointment'),
        ),
    ]
