# Generated by Django 2.0.4 on 2019-01-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_app', '0019_auto_20190119_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='amount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='principle',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
