# Generated by Django 2.0.4 on 2019-01-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss_app', '0020_auto_20190119_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='principle',
            new_name='principal',
        ),
    ]
