# Generated by Django 2.0.4 on 2019-03-26 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ss_app', '0023_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ss_app.Staff'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
