# Generated by Django 2.0.4 on 2019-03-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_app', '0024_auto_20190326_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='target_date',
            field=models.DateField(null=True),
        ),
    ]
