# Generated by Django 2.0.4 on 2019-03-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_app', '0025_task_target_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='bookable',
            field=models.BooleanField(default=False),
        ),
    ]
